import { Brain, TrendingUp, AlertTriangle, Activity, CheckCircle } from 'lucide-react';
import { RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer, Tooltip } from 'recharts';

const radarData = [
  { feature: 'HR Baseline', score: 88 },
  { feature: 'SpO₂ Stability', score: 92 },
  { feature: 'HRV Pattern', score: 74 },
  { feature: 'ECG Morphology', score: 86 },
  { feature: 'PPG Quality', score: 76 },
  { feature: 'Anomaly Risk', score: 18 },
];

const insights = [
  {
    type: 'good', icon: <CheckCircle size={16}/>, title: 'Within Personalized Baseline',
    desc: 'Heart rate has remained within the learned baseline range (66–80 BPM) for 95% of today\'s monitoring session. No baseline drift detected.',
    models: ['Personalized FL', 'Baseline Learner'],
    confidence: 0.91,
  },
  {
    type: 'good', icon: <CheckCircle size={16}/>, title: 'SpO₂ Consistently Normal',
    desc: 'SpO₂ has not dropped below 96.9% during the monitoring session. Perfusion index is within expected range for this synthetic client profile.',
    models: ['PPG Processor', 'SpO₂ Analyzer'],
    confidence: 0.87,
  },
  {
    type: 'warning', icon: <AlertTriangle size={16}/>, title: 'HRV Shows Mild Reduction',
    desc: 'SDNN and RMSSD are slightly below the user\'s 30-day moving average. This may reflect minor physiological variation in synthetic data.',
    models: ['ECG Processor', 'Personalized FL'],
    confidence: 0.72,
  },
  {
    type: 'info', icon: <Brain size={16}/>, title: 'Personalization Improving Accuracy',
    desc: 'The personalized model correctly classified 3 additional borderline cases compared to the global model. Local F1 improved from 0.831 → 0.862 after 7 personalization rounds.',
    models: ['QAPFL', 'Personal Model'],
    confidence: 0.89,
  },
];

const typeColor: Record<string, string> = {
  good: 'border-green-800/40 bg-green-900/10 text-green-300',
  warning: 'border-amber-800/40 bg-amber-900/10 text-amber-300',
  info: 'border-blue-800/40 bg-blue-900/10 text-blue-300',
};

export default function AIInsightsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white flex items-center gap-2">
          <Brain size={24} className="text-purple-400"/> AI Insights
        </h1>
        <p className="text-gray-400 text-sm mt-1">Automated analysis from QAPFL personalized model — Synthetic Demo Data</p>
      </div>

      <div className="bg-amber-900/20 border border-amber-800/30 rounded-xl p-4 text-amber-300 text-sm">
        ⚠️ <strong>Research Output:</strong> These AI insights are generated by pattern recognition models on synthetic physiological data. They do not constitute medical advice, diagnosis, or treatment recommendations.
      </div>

      <div className="grid grid-cols-3 gap-6">
        {/* Radar chart */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-5">
          <h3 className="text-white font-medium mb-4">Health Radar</h3>
          <ResponsiveContainer width="100%" height={240}>
            <RadarChart data={radarData}>
              <PolarGrid stroke="#374151"/>
              <PolarAngleAxis dataKey="feature" tick={{ fill: '#9ca3af', fontSize: 10 }}/>
              <PolarRadiusAxis domain={[0, 100]} tick={{ fill: '#6b7280', fontSize: 9 }}/>
              <Tooltip contentStyle={{ backgroundColor: '#1f2937', border: '1px solid #374151', borderRadius: '8px' }}/>
              <Radar name="Health" dataKey="score" stroke="#a78bfa" fill="#a78bfa" fillOpacity={0.25} strokeWidth={2}/>
            </RadarChart>
          </ResponsiveContainer>
          <p className="text-gray-600 text-xs mt-2 text-center">Scores from personalized model — synthetic data</p>
        </div>

        {/* Insights */}
        <div className="col-span-2 space-y-3">
          {insights.map((insight, i) => (
            <div key={i} className={`border rounded-xl p-4 ${typeColor[insight.type]}`}>
              <div className="flex items-start gap-3">
                <span className="flex-shrink-0 mt-0.5">{insight.icon}</span>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-medium text-sm">{insight.title}</span>
                    <span className="text-xs opacity-60 ml-auto">Confidence: {(insight.confidence * 100).toFixed(0)}%</span>
                  </div>
                  <p className="text-xs opacity-80 leading-relaxed">{insight.desc}</p>
                  <div className="flex gap-1 mt-2">
                    {insight.models.map(m => (
                      <span key={m} className="text-xs px-2 py-0.5 bg-black/20 rounded-full opacity-70">{m}</span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
